spring.application.name=backend
#spring.mongodb.uri=mongodb://localhost:27017/workflow_db
server.port=${PORT:8080}

spring.mongodb.uri=mongodb+srv://misaelvediaeyz_db_user:aGSZKDfzg4Doe5cH@cluster0.dlbljqm.mongodb.net/workflow_db?retryWrites=true&w=majority&appName=Cluster0